# Generated by Django 4.0 on 2022-03-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_user_config_normal_offers_user_config_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_config',
            name='total_received_numbers',
            field=models.IntegerField(default=0),
        ),
    ]
