# Generated by Django 4.0 on 2022-03-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_user_config_total_received_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_config',
            name='numbers_of_one_ad',
            field=models.IntegerField(default=0),
        ),
    ]
