# Generated by Django 4.0 on 2022-03-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_user_config_numbers_of_one_ad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page_Controler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('hover_title', models.URLField(max_length=100)),
                ('url', models.URLField(max_length=100)),
                ('new_tab', models.BooleanField(default=False)),
                ('activate', models.BooleanField(default=True)),
            ],
        ),
    ]
