# Generated by Django 4.0 on 2022-03-12 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Normal_offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_digits', models.IntegerField()),
                ('free_number', models.IntegerField(default=0)),
                ('numbers_of_one_ad', models.IntegerField(default=100)),
                ('numbers_of_one_ad_text', models.CharField(default='لم يتم تخصيص نص', max_length=28)),
                ('text_1', models.CharField(default='لم يتم تخصيص نص', max_length=28)),
                ('text_2', models.CharField(default='لم يتم تخصيص نص', max_length=28)),
                ('message_type', models.CharField(choices=[('text', 'text'), ('text + image', 'text + image')], default='text', max_length=50)),
                ('message_type_text', models.CharField(default='لم يتم تخصيص نص', max_length=28)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.normal_offers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.profile')),
            ],
        ),
    ]
