# Generated by Django 4.0 on 2022-03-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normal_offers',
            name='unique_id',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
    ]
