# Generated by Django 4.0 on 2022-03-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_normal_offers_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_process',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payment_process',
            name='card_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_process',
            name='done',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payment_process',
            name='expiry_month',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_process',
            name='expiry_year',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_process',
            name='full_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_process',
            name='security_code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
