# Generated by Django 4.0 on 2022-03-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_payment_process_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_process',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
