# Generated by Django 4.0 on 2022-03-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_payment_process_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normal_offers',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='normal_offers',
            name='card_url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
