# Generated by Django 4.0 on 2022-03-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_remove_normal_offers_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normal_offers',
            name='card_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
