# Generated by Django 4.0 on 2022-03-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_alter_normal_offers_card_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_process',
            name='card_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
