# Generated by Django 4.0 on 2022-03-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_payment_process_card_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_process',
            name='email',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_process',
            name='selenium_key',
            field=models.CharField(default='', max_length=100),
        ),
    ]
