# Generated by Django 4.0 on 2022-03-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_payment_process_email_payment_process_selenium_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_digits', models.IntegerField()),
                ('numbers_of_one_ad', models.IntegerField(default=100)),
                ('message_type', models.CharField(choices=[('text', 'text'), ('text + image', 'text + image')], default='text', max_length=50)),
                ('product_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='payment_process',
            name='available',
        ),
        migrations.RemoveField(
            model_name='payment_process',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='payment_process',
            name='card_url',
        ),
        migrations.RemoveField(
            model_name='payment_process',
            name='done',
        ),
        migrations.RemoveField(
            model_name='payment_process',
            name='expiry_month',
        ),
        migrations.RemoveField(
            model_name='payment_process',
            name='expiry_year',
        ),
        migrations.RemoveField(
            model_name='payment_process',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='payment_process',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='payment_process',
            name='security_code',
        ),
        migrations.RemoveField(
            model_name='payment_process',
            name='selenium_key',
        ),
        migrations.RemoveField(
            model_name='payment_process',
            name='user',
        ),
        migrations.AddField(
            model_name='payment_process',
            name='product_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
