# Generated by Django 4.0 on 2022-03-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_offers_remove_payment_process_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='product_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
