# Generated by Django 4.0 on 2022-03-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0011_payment_process_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_process',
            name='payment_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
